### ISSUE TITLE
Job Script Integrity

### ISSUE THREAD

**Issue by jhl667** [ARTbio/GalaxyKickStart#263]
Hi all,

I’m installing via GalaxyKickStart…
I’m getting the following error:

```
galaxy.jobs.runners ERROR 2017-11-06 19:14:05,263 (19) Failure preparing job
Traceback (most recent call last):
  File "/home/exacloud/lustre1/galaxydev/galaxyuser/lib/galaxy/jobs/runners/__init__.py", line 175, in prepare_job
    modify_command_for_container=modify_command_for_container
  File "/home/exacloud/lustre1/galaxydev/galaxyuser/lib/galaxy/jobs/runners/__init__.py", line 209, in build_command_line
    container=container
  File "/home/exacloud/lustre1/galaxydev/galaxyuser/lib/galaxy/jobs/command_factory.py", line 84, in build_command
    externalized_commands = __externalize_commands(job_wrapper, external_command_shell, commands_builder, remote_command_params)
  File "/home/exacloud/lustre1/galaxydev/galaxyuser/lib/galaxy/jobs/command_factory.py", line 143, in __externalize_commands
    write_script(local_container_script, script_contents, config)
  File "/home/exacloud/lustre1/galaxydev/galaxyuser/lib/galaxy/jobs/runners/util/job_script/__init__.py", line 112, in write_script
    _handle_script_integrity(path, config)
  File "/home/exacloud/lustre1/galaxydev/galaxyuser/lib/galaxy/jobs/runners/util/job_script/__init__.py", line 147, in _handle_script_integrity
    raise Exception("Failed to write job script, could not verify job script integrity.")
Exception: Failed to write job script, could not verify job script integrity.
galaxy.model.metadata DEBUG 2017-11-06 19:14:05,541 Cleaning up external metadata files
galaxy.model.metadata DEBUG 2017-11-06 19:14:05,576 Failed to cleanup MetadataTempFile temp files from /home/exacloud/lustre1/galaxydev/galaxyuser/database/jobs/000/19/metadata_out_HistoryDatasetAssociation_16_I8bhLX: No JSON object could be decoded

```
I would like to further understand what it means to not verify integrity of a job script.  Does this just mean there is a permissions error?  Ownership doesn’t match up?

Thanks,
John

NOTE: This was cross-posted to galaxy-dev.

**Comment by drosofff** [comment]
@jhl667 Did you get an answer ?
