### ISSUE TITLE
User Management interface in admin menu not working

### ISSUE THREAD

**Issue by amir-azizi** [ARTbio/GalaxyKickStart#414]
Hi,

We have installed GKS on a local machine for our lab. Everything works correctly, except for the "Users" option under "User Management" in the administration section. Clicking on this link just brings up the loading icon and nothing happens. The following errors are raised in the `uwsgi.log` file as a result:

`172.20.**.** - - [25/Jul/2022:10:10:34 +0450] "GET /admin/users_list?__identifer=ibmm6ibv30n HTTP/1.1" 500 - "http://172.20.***.***/admin/users?__identifer=ibmm6ibv30n" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15"
Traceback (most recent call last):
  File "/2050/galaxy_amir/galaxy/galaxy/lib/galaxy/web/framework/middleware/error.py", line 154, in __call__
    app_iter = self.application(environ, sr_checker)
  File "/2050/galaxy_amir/galaxy/galaxy/.venv/lib/python3.8/site-packages/paste/recursive.py", line 85, in __call__
    return self.application(environ, start_response)
  File "/2050/galaxy_amir/galaxy/galaxy/.venv/lib/python3.8/site-packages/paste/httpexceptions.py", line 640, in __call__
    return self.application(environ, start_response)
  File "/2050/galaxy_amir/galaxy/galaxy/lib/galaxy/web/framework/base.py", line 138, in __call__
    return self.handle_request(environ, start_response)
  File "/2050/galaxy_amir/galaxy/galaxy/lib/galaxy/web/framework/base.py", line 217, in handle_request
    body = method(trans, **kwargs)
  File "/2050/galaxy_amir/galaxy/galaxy/lib/galaxy/web/framework/decorators.py", line 63, in call_and_format
    rval = func(self, trans, *args, **kwargs)
  File "/2050/galaxy_amir/galaxy/galaxy/lib/galaxy/web/framework/decorators.py", line 106, in decorator
    return func(self, trans, *args, **kwargs)
  File "/2050/galaxy_amir/galaxy/galaxy/lib/galaxy/webapps/galaxy/controllers/admin.py", line 629, in users_list
    return self.user_list_grid(trans, **kwd)
  File "/2050/galaxy_amir/galaxy/galaxy/lib/galaxy/web/framework/helpers/grids.py", line 897, in __call__
    value = unicodify(column.get_value(trans, self, item))
  File "/2050/galaxy_amir/galaxy/galaxy/lib/galaxy/webapps/galaxy/controllers/admin.py", line 75, in get_value
    return self.format(user.galaxy_sessions[0].update_time)
  File "/2050/galaxy_amir/galaxy/galaxy/lib/galaxy/web/framework/helpers/__init__.py", line 39, in time_ago
    return format_timedelta(x - datetime.utcnow(), threshold=1, add_direction=True, **kwargs)
  File "/2050/galaxy_amir/galaxy/galaxy/.venv/lib/python3.8/site-packages/babel/dates.py", line 930, in format_timedelta
    locale = Locale.parse(locale)
  File "/2050/galaxy_amir/galaxy/galaxy/.venv/lib/python3.8/site-packages/babel/core.py", line 331, in parse
    raise UnknownLocaleError(input_id)
babel.core.UnknownLocaleError: unknown locale 'az_IR'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/2050/galaxy_amir/galaxy/galaxy/lib/galaxy/web/framework/middleware/batch.py", line 85, in __call__
    return self.application(environ, start_response)
  File "/2050/galaxy_amir/galaxy/galaxy/lib/galaxy/web/framework/middleware/request_id.py", line 15, in __call__
    return self.app(environ, start_response)
  File "/2050/galaxy_amir/galaxy/galaxy/lib/galaxy/web/framework/middleware/xforwardedhost.py", line 23, in __call__
    return self.app(environ, start_response)
  File "/2050/galaxy_amir/galaxy/galaxy/lib/galaxy/web/framework/middleware/translogger.py", line 69, in __call__
    return self.application(environ, replacement_start_response)
  File "/2050/galaxy_amir/galaxy/galaxy/lib/galaxy/web/framework/middleware/error.py", line 162, in __call__
    start_response('500 Internal Server Error',
  File "/2050/galaxy_amir/galaxy/galaxy/lib/galaxy/web/framework/middleware/translogger.py", line 68, in replacement_start_response
    return start_response(status, headers, exc_info)
SystemError: <built-in function uwsgi_spit> returned a result with an error set
[pid: 906651|app: 0|req: 329/664] 172.20.**.** () {44 vars in 852 bytes} [Mon Jul 25 10:10:34 2022] GET /admin/users_list?__identifer=ibmm6ibv30n => generated 0 bytes in 25 msecs (HTTP/1.1 500) 1 headers in 63 bytes (0 switches on core 1)`

We'd appreciate it if you could have a look and let us know what might be going wrong here.

Thanks, 
Amir

**Comment by drosofff** [comment]
Hi @amir-azizi 
Sorry for my delayed follow-up, I hope you found the bug in the meantime...

In any case, here is a bit of contexte to understand why I am not going to work on your issue:

The last version of Galaxy release_22.05 has [dropped the use of uwsgi](https://docs.galaxyproject.org/en/latest/releases/22.05_announce.html#:~:text=Galaxy%20is%20now%20exclusively%20a%20FastAPI%20application).

Therefore, I am going to update GalaxyKickStart which currently installs Galaxy release_21.05 as a WSGI application.
It may takes a bit of time to migrate the Ansible playbook (as I understand it, the Galaxy devteam [is also on this spot](https://docs.galaxyproject.org/en/latest/admin/migrating_to_gunicorn.html#:~:text=we%20are%20working%20on%20updating%20the%20Ansible%20roles%20for%20installing%20Galaxy.)), however my bet is that your issue will be fixed when this is done.
Cheers
Chris

**Comment by amir-azizi** [comment]
Thanks Chris.

Looking forward to try the new GKS.

Cheers,
Amir
